version: "3.9"
services:
    app:
        build:
            args:
                user: alireza
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: php
        container_name: royalcode-php
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - crm
    db:
        image: mysql:8.0.20
        container_name: crm-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        tty: true
        volumes:
            - ./services/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - crm
    nginx:
        image: nginx:stable-alpine
        container_name: crm-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./services/nginx:/etc/nginx/conf.d
        networks:
            - crm
    composer:
        networks:
            - crm
        image: composer:latest
        container_name: crm-composer
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - app
networks:
    crm:
        driver: bridge
